services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME:-cinema}
      POSTGRES_USER: ${DB_USER:-cinema}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-cinema}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
             gunicorn cinema_service.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      # dockerfile: Dockerfile   # додай, якщо у frontend є Dockerfile і він не стандартний
    environment:
      VITE_API_URL: "http://localhost:8000/api"
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install && npm run dev -- --host"

volumes:
  db_data:
